name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'module/**'
      - 'update.json'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Force a Release?'
        required: true
        type: boolean
        default: false
      mark_prerelease:
        description: "Mark as prerelease?"
        required: true
        type: boolean
        default: false
      mark_draft:
        description: "Mark release as draft?"
        required: true
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set variables
        id: setup
        env:
          CREATE_RELEASE: ${{ inputs.create_release }}
        run: |
          MODULE_NAME="HyperUnlocked"
          MODULE_DESC="A Magisk/KernelSU/APatch module made to unlock all high-end features possible to be unlocked on low-end xiaomi devices."
          CHANGELOG_FILE="$(pwd)/CHANGELOG.md"
          
          CURRENT_VERSION_CODE=$(jq -r .versionCode update.json)
          PREVIOUS_VERSION_CODE=$(jq -r .versionCode <(git show HEAD~1:update.json))
          COMMIT_ID=$(git rev-parse --short HEAD)
          echo "VERSION=$(jq -r .version update.json)" >> $GITHUB_ENV
          echo "MODULE_PATH=$(pwd)/module/" >> $GITHUB_ENV
          echo "CHANGELOG_RAW=$(git diff HEAD^ HEAD -- ${CHANGELOG_FILE} | grep '^+[^+]' | sed 's/^+//')"
          {
            echo "CHANGELOG<<EOF"
            echo -e "## ${MODULE_NAME}\n${MODULE_DESC}\n\n---\n\n${CHANGELOG_RAW}"
            echo "EOF"
          } >> $GITHUB_ENV
          
          if [ "$CURRENT_VERSION_CODE" -gt "$PREVIOUS_VERSION_CODE" ] || [ "$CREATE_RELEASE" == "true" ]; then
            echo "version_changed=true" >> $GITHUB_ENV
            echo "ZIP_NAME=$MODULE_NAME" >> $GITHUB_ENV
          else
            echo "version_changed=false" >> $GITHUB_ENV
            echo "ZIP_NAME=${MODULE_NAME}_${CURRENT_VERSION_CODE}-${COMMIT_ID}" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.MODULE_PATH }}**

      - name: Compressing files
        if: ${{ env.version_changed == 'true' }}
        run: |
          echo "Compressing files..."
          cd ${{ env.MODULE_PATH }}
          zip -r ${{ env.ZIP_NAME }}.zip *
          echo "Created zip file: ${{ env.ZIP_NAME }}.zip"
          mv *.zip ../

      - name: Create release
        if: ${{ env.version_changed == 'true' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "${{ env.ZIP_NAME }}.zip"
          tag_name: "${{ env.VERSION }}"
          name: "Release ${{ env.VERSION }}"
          body: "${{ env.CHANGELOG }}"
          draft: ${{ inputs.mark_draft }}
          prerelease: ${{ inputs.mark_prerelease }}
